using System.Numerics;
 using ImGuiNET;
 using MadEngine.Core;
 using OpenTK.Windowing.Common;
 
 namespace MadEditor;
 
 public class ViewportDrawer : IPanelDrawer
 {
     public string Name => "Viewport";
     public PanelRegion PanelRegion { get; set; } = PanelRegion.Center;
     public void Draw(EditorUIContext context)
     {
         Vector2 availableSpace = ImGui.GetContentRegionAvail();
        
         float availableW = availableSpace.X;
         float availableH = availableSpace.Y;
       
         // 2. Safely trigger a render texture resize pass if the user drags the split bar
         if (availableW > 1 && availableH > 1)
         {
             if (availableW != context.ViewportSize.X || availableH != context.ViewportSize.Y)
             {
                 // Synchronize your rendering context data tracker dimensions
                 context.ViewportSize = new Vector2(availableW, availableH);
                 context.SceneFbo.Resize((int)availableW, (int)availableH);

                 // Re-calculate the matrix ratios inside your camera pipeline
                 Camera cam = context.CameraObject.GetComponent<Camera>()!;
                 cam.Width = (int)availableW;
                 cam.Height = (int)availableH;
             }
         }
        
         // 3. Keep your input capture context routines perfectly intact
         if (ImGui.IsWindowHovered() && ImGui.IsMouseClicked(ImGuiMouseButton.Right))
             context.Window!.CursorState = CursorState.Grabbed;
        
         // 4. Render the output image buffer generated by your OpenTK Framebuffer Object (FBO)
         // Ensure you use context.ViewportSize (which is now perfectly locked to the available space)
         ImGui.Image(context.SceneFbo.ColorTexture, context.ViewportSize, new Vector2(0, 1), new Vector2(1, 0));

         // 5. Draw the floating user helper text guide overlay seamlessly
         if (context.Window!.CursorState == CursorState.Normal)
         {
             // Position the text relative to the content area canvas top-left corner
             ImGui.SetCursorPos(new Vector2(8, ImGui.GetFrameHeight() + 4));
             ImGui.TextDisabled("Right-click + WASD to fly  |  Esc to release");
         }
     }
 }